name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'npm'
      - name: Install yarn
        run: nmp yarn install
      - name: Linting code
        uses: yarn lint       
        

